CAMPAIGN:
  ID: 1T8rAqeU2J_gEvryhRIqWVtmh6zxwE2sRXX2Iqf__GOg
  URL: https://docs.google.com/spreadsheets/d/1T8rAqeU2J_gEvryhRIqWVtmh6zxwE2sRXX2Iqf__GOg
  CSV: https://docs.google.com/spreadsheets/d/e/2PACX-1vT2YmAC_qniom8yEUVqq-dFRG-QiyLaFym9xw_sFss5viPwvzpEbusJ9BlgXwuat-Hi5yvUnSvnZdB2/pub?output=csv
CHAT:
  ID: 1mQilDBHj6myUG1ghT1vLUotJfg2jIB2G0nkoGWLIrEs
  URL: https://docs.google.com/spreadsheets/d/1mQilDBHj6myUG1ghT1vLUotJfg2jIB2G0nkoGWLIrEs
  CSV: https://docs.google.com/spreadsheets/d/e/2PACX-1vSGilzY7sHNiu5FkR5TzOmyGKkvlyukgl_WhwJ1_jySIgZCcstirCB3NQy6PcaufH7W1wFPlDEQiosR/pub?output=csv
CHATGROUP:
  ID: 1V6_vzLVqZaVBZHmKuHSwVtUt2AWWbLO-fNgZWEQ0QSM
  URL: https://docs.google.com/spreadsheets/d/1V6_vzLVqZaVBZHmKuHSwVtUt2AWWbLO-fNgZWEQ0QSM
  CSV: https://docs.google.com/spreadsheets/d/e/2PACX-1vSNdaxXPa40Ivxko3dDNUVdIOt0iqbnyKShaoiGDwHAM0uzVkFY-mjsrGTFqxOpB487vIx7PcpSgUwk/pub?output=csv
NEWS:
  ID: 1jSqK0uogmshIa4I-QTXyNWv-TUOt3uP5Tgg2rXUM1D0
  URL: https://docs.google.com/spreadsheets/d/1jSqK0uogmshIa4I-QTXyNWv-TUOt3uP5Tgg2rXUM1D0
  CSV: https://docs.google.com/spreadsheets/d/e/2PACX-1vQhIPGR7xXreZHzgURzABKCeyZTltRWa5osj3OBG-0zph0iEfycqvYWTE4kzWBky7aStivxkSGeB_U8/pub?output=csv
USERS:
  ID: 1h7poZxyPUS79nq9WaMMNxsmc7PsBQaxhqZ3ZTKMdfGA
  URL: https://docs.google.com/spreadsheets/d/1h7poZxyPUS79nq9WaMMNxsmc7PsBQaxhqZ3ZTKMdfGA
  CSV: https://docs.google.com/spreadsheets/d/e/2PACX-1vRYWOqjGRSWODteFMKtelqPxAWMAzmXckvuVqyv79t70T1n_tAKOWRhkW11ixZHr8Cj1luSY32C0ZcJ/pub?output=csv
ROLES:
  ID: 1BwxVXs8ip5cMvwYDyZMtlyJ91jh-BN6RFedIsk_uGYk
  URL: https://docs.google.com/spreadsheets/d/1BwxVXs8ip5cMvwYDyZMtlyJ91jh-BN6RFedIsk_uGYk
  CSV: https://docs.google.com/spreadsheets/d/e/2PACX-1vTtUT884RpDKoydKUqBBYyxmPe6lvE6j2hMHc0ovph52ijv4XDqP9O2brXIZnScuaMf4HK0uY4xqHSI/pub?output=csv
